name: Java CI

on:
  workflow_dispatch:
  push:
    branches: [ ci-build, nit-test-time-scenario, unit-test-missing-beans ]
  pull_request:
    branches: [ ci-build, unit-test-time-scenario, unit-test-missing-beans ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Use Temurin OpenJDK distribution

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository # Cache Maven local repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Key based on OS and pom.xml hash
          restore-keys: |
            ${{ runner.os }}-maven- # Restore key for previous caches

      - name: Build with Maven
        run: mvn clean compile # Clean and compile the project

      - name: Run Unit Tests
        run: mvn test # Execute all unit tests
